package group.gnometrading.gateways.exchanges.polymarket.intl;

import static org.junit.jupiter.api.Assertions.assertEquals;

import group.gnometrading.gateways.outbound.exchanges.polymarket.intl.PolymarketIntlAuthHeaders;
import java.nio.charset.StandardCharsets;
import java.util.Base64;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class PolymarketIntlAuthHeadersTest {

    private static final String API_KEY = "test-api-key";
    private static final String PASSPHRASE = "test-passphrase";
    private static final String ADDRESS = "0xDeadBeef";

    // base64("test-secret") = "dGVzdC1zZWNyZXQ="
    private static final String BASE64_SECRET = "dGVzdC1zZWNyZXQ=";
    private static final byte[] DECODED_SECRET = Base64.getDecoder().decode(BASE64_SECRET);

    private PolymarketIntlAuthHeaders headers;

    @BeforeEach
    void setUp() {
        headers = new PolymarketIntlAuthHeaders(API_KEY, BASE64_SECRET, PASSPHRASE, ADDRESS);
    }

    @Test
    void accessorsReturnConstructorValues() {
        assertEquals(API_KEY, headers.apiKey());
        assertEquals(PASSPHRASE, headers.passphrase());
        assertEquals(ADDRESS, headers.address());
    }

    // Generated by py-clob-client-v2's build_hmac_signature. The secret contains '-' and '_', and the GET
    // signature a '-', so standard (non-URL-safe) base64 on either side fails these.
    private static final String URL_SAFE_SECRET = "4OHi4-Tl5ufo6err7O3u7_Dx8vP09fb3-Pn6-_z9_v8=";
    private static final long TIMESTAMP = 1759350000L;

    @Test
    void signaturesMatchReferenceClient() {
        final PolymarketIntlAuthHeaders reference =
                new PolymarketIntlAuthHeaders(API_KEY, URL_SAFE_SECRET, PASSPHRASE, ADDRESS);

        final byte[] post = "{\"order\":{\"salt\":1},\"owner\":\"k\"}".getBytes(StandardCharsets.UTF_8);
        reference.sign(TIMESTAMP, "POST", "/order", post, 0, post.length);
        assertEquals("K94i9MiUG9ivsBpQO3cIgspu4ckIk175Qt7DBg9jBno=", reference.signature());
        assertEquals("1759350000", reference.timestamp());

        final byte[] delete = "{\"orderID\":\"0xabc\"}".getBytes(StandardCharsets.UTF_8);
        reference.sign(TIMESTAMP, "DELETE", "/order", delete, 0, delete.length);
        assertEquals("Zp21kYIP4cRdMwMHctMmJSpSjL0XsR2qEHTpP1IzIO0=", reference.signature());

        reference.sign(TIMESTAMP, "GET", "/data/order/0xabc", null, 0, 0);
        assertEquals("YMCLmvAW6KCEY6lREO5IngSYsaMh-6dCOMRTR-ozBSY=", reference.signature());
    }

    @Test
    void signWithNullBodyTreatsAsEmpty() throws Exception {
        headers.sign("GET", "/data", null, 0, 0);
        final String nullSig = headers.signature();
        final String nullTs = headers.timestamp();

        headers.sign("GET", "/data", null, 0, 0);
        final String emptySig = headers.signature();

        if (nullTs.equals(headers.timestamp())) {
            assertEquals(nullSig, emptySig);
        }
    }

    @Test
    void timestampIsCurrentUnixSeconds() {
        headers.sign("GET", "/", null, 0, 0);
        final long now = System.currentTimeMillis() / 1000L;
        final long ts = Long.parseLong(headers.timestamp());
        // Allow 2-second window to account for potential delay
        assertEquals(now, ts, 2);
    }
}
